### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by caarlos0** [joinville-gophers/discussions#1]
E aí pessoal!

Que tal bolarmos uma logo pro meetup?

Idéias iniciais:

- gopher segurando
  - guarda-chuva (ou usando capa de chuva)
  - chineque (ou outra comida típica)

se alguém tiver mais idéias e/ou quiser tentar desenhar algo, manda ver!

**Comment by jhonmike** [comment]
[WIP] ...
<img src="https://user-images.githubusercontent.com/2499937/35365932-0251be2c-015e-11e8-96a5-69a5019d7807.jpeg" width="400" />

**Comment by caarlos0** [comment]
WIP: 

![image](https://user-images.githubusercontent.com/245435/35387893-bb97d48e-01b8-11e8-8f49-ad7d12fe3f54.png)

e também um gophrida:

![image](https://user-images.githubusercontent.com/245435/35388866-abd1ca6a-01bc-11e8-9408-e1c6585cc88d.png)


por @carinebecker

**Comment by caarlos0** [comment]
WIP:

![image](https://user-images.githubusercontent.com/245435/35456310-26f4caa8-02bc-11e8-8a8c-4ca5cb9f5340.png)

**Comment by caarlos0** [comment]
agora segurando a chineque:

![image](https://user-images.githubusercontent.com/245435/35734772-6c0d82e0-0809-11e8-94c0-44d36e0765b3.png)

o que acham?

**Comment by caarlos0** [comment]
cc/ @joinville-gophers/gophers

**Comment by raduq** [comment]
Poderia ter um com o guarda chuva + camiseta chineque

**Comment by tmatias** [comment]
+1 pra  versão com o chineque, mt bom, :smile:.

**Comment by caarlos0** [comment]
> Poderia ter um com o guarda chuva + camiseta chineque

vou ver se a @carinebecker faz um desses tbm :)

**Comment by caarlos0** [comment]
setei como logo pra ver como fica!

olhem ai!

https://github.com/joinville-gophers

**Comment by alfakini** [comment]
Não fode, que foda!

**Comment by caarlos0** [comment]
bom, vou fechar essa aqui por hora!

valeussss todo mundo

**Comment by merencia** [comment]
Seguindo a linha do guarda chuva:
![whatsapp image 2018-02-23 at 11 03 15](https://user-images.githubusercontent.com/1686635/36600056-ff98b49e-188f-11e8-9aff-3b8fbb9bc938.jpeg)
