### ISSUE TITLE
Próximo meetup: 27/02

### ISSUE THREAD

**Issue by caarlos0** [joinville-gophers/discussions#3]
Boa tarde @joinville-gophers/gophers!

A principio, meetup confirmado pra dia 27/02, aqui na @ContaAzul!

[Call for papers aberto!](https://github.com/joinville-gophers/cfp) Podem submeter palestras e encher a paciencia dos colegas pra submeter também!

[Evento no meetup.com](https://www.meetup.com/Joinville-Go-Meetup/events/247548485/)

**Comment by tmatias** [comment]
> encher a paciencia dos colegas pra submeter também!

@rogerfernandes

**Comment by caarlos0** [comment]
@joinville-gophers/gophers  Ninguém submeteu palestras ainda 😞

**Comment by schweigert** [comment]
@caarlos0 encontrei o grupo de vocês, e tenho interesse em submeter uma palestra. Como posso entrar em contato?

**Comment by caarlos0** [comment]
oi @Schweigert,

que massa!

É só submeter uma issue no projeto cfp -> https://github.com/joinville-gophers/cfp

Valeu!

**Comment by tmatias** [comment]
@Schweigert massa! Temos um canal #joinville no slack, se quiser discutir com a gente, é só entrar lá, ou também pode chamar pessoalmente (eu ou o @caarlos0) pelo slack sobre qualquer dúvida sobre o meetup.
 
Link do invite pro canal: https://invite.slack.golangbridge.org/.

**Comment by schweigert** [comment]
Vou chamar no Slack! :tada:

**Comment by caarlos0** [comment]
Feito!

Muito obrigado todo mundo que veio, em especial aos palestrantes e ao pessoal que ajudou na organização!

Os links das palestras:

- https://talks.godoc.org/github.com/joinville-gophers/presentations/go110.slide
- https://talks.godoc.org/github.com/joinville-gophers/presentations/joinville.slide

Source delas está em https://github.com/joinville-gophers/presentations

Quem tem interesse em palestrar, já pode preencher no nosso call for papers: https://github.com/joinville-gophers/cfp

Se tem algum assunto especifico que você gostaria de ver em alguma palestra, pode sugerir nessa issue: https://github.com/joinville-gophers/discussions/issues/4

É isso, valeu!!
