### ISSUE TITLE
Próximo encontro

### ISSUE THREAD

**Issue by caarlos0** [joinville-gophers/discussions#5]
Vamos marcar o próximo?

cc/ @joinville-gophers/gophers

**Comment by B0go** [comment]
@caarlos0 se fizer sentido fazer aqui na ContaAzul novamente eu posso falar com o pessoal! Só preciso de umas 2-3 datas para caso tenha alguma coisa no dia

**Comment by caarlos0** [comment]
vamos fazer num sábado? ai o pessoal de floripa pode vir também...

**Comment by B0go** [comment]
> vamos fazer num sábado? ai o pessoal de floripa pode vir também...

Sim, inclusive acho mais fácil de achar lugar tb

**Comment by t-bonatti** [comment]
@caarlos0 
É possível fazer aqui na Softville no auditório, mas somente durante a semana (a noite)
No sábado já esta ocupado até setembro =/

**Comment by tmatias** [comment]
Acho legal fazer no sábado mesmo.

Durante a semana além de as faculdades terem aula, o trânsito e a distância aqui pro Distrito Industrial também atrapalham.

O próximo meetup de Floripa tá marcado pra 4 de agosto, então seria interessante marcamos pro começo de julho, sugestão: dia 7 de julho.

**Comment by caarlos0** [comment]
@tmatias nesses dias eu possivelmente estarei fora :( 

vou confirmar e aviso :)

**Comment by caarlos0** [comment]
ainda nao sei :(

**Comment by caarlos0** [comment]
Entao, nao posso no dia 7.


O que acham de 28/07?

**Comment by caarlos0** [comment]
Acho que dia 28 não vai mais dar não né hehe

**Comment by caarlos0** [comment]
Meu, já faz quase 1 ano...

**Comment by B0go** [comment]
Bora fazer acontecer então?

**Comment by caarlos0** [comment]
acho justo! o pessoal da RD tava querendo organizar um aqui em joinville... 

alguem sabe o arroba do Rodrigo Miguel?

**Comment by B0go** [comment]
@caarlos0 a ContaAzul está um pouco complicado agora por conta das reformas (creio) mas podemos avaliar fazer no Agora Hub (do Agora tech park) porém não faço ideia como funciona e teria que avaliar

Mas já vi alguns eventos rolarem lá...
vou verificar e falamos
